web:
  build: .
  ports:
    - "8000:8000"
  links:
    - mysql:mysql
  env_file: .env
  command: /code/manage.py runserver 0.0.0.0:8000

mysql:
  image: mysql:latest
  environment:
    - MYSQL_DATABASE=django
    - MYSQL_ROOT_PASSWORD=mysql
  ports:
    - "3306:3306"
