# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 03:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(default=None, max_length=20)),
                ('metas', jsonfield.fields.JSONField(default=None)),
                ('headers', jsonfield.fields.JSONField()),
                ('parameters', jsonfield.fields.JSONField()),
                ('body', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('user', models.CharField(default=None, max_length=45)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.URL'),
        ),
    ]
